// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJqpdro7Qd7bz_Oly10KrL-Dg9HXPpBag',
    appId: '1:684377007786:web:724821af352be74c0312d3',
    messagingSenderId: '684377007786',
    projectId: 'portfolio-m7m7',
    authDomain: 'portfolio-m7m7.firebaseapp.com',
    storageBucket: 'portfolio-m7m7.firebasestorage.app',
    measurementId: 'G-XEWYW3GVDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcLF7suMiZlLRd_rK7-nZZxHSl3M3njUY',
    appId: '1:684377007786:android:cbb5fdfff68cdb300312d3',
    messagingSenderId: '684377007786',
    projectId: 'portfolio-m7m7',
    storageBucket: 'portfolio-m7m7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx_yqVxop60zJ454svBCQGgsoWJm8HwdQ',
    appId: '1:684377007786:ios:9793d74bff584c8f0312d3',
    messagingSenderId: '684377007786',
    projectId: 'portfolio-m7m7',
    storageBucket: 'portfolio-m7m7.firebasestorage.app',
    iosBundleId: 'com.example.personalPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx_yqVxop60zJ454svBCQGgsoWJm8HwdQ',
    appId: '1:684377007786:ios:9793d74bff584c8f0312d3',
    messagingSenderId: '684377007786',
    projectId: 'portfolio-m7m7',
    storageBucket: 'portfolio-m7m7.firebasestorage.app',
    iosBundleId: 'com.example.personalPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJqpdro7Qd7bz_Oly10KrL-Dg9HXPpBag',
    appId: '1:684377007786:web:d307f2f3ca736d590312d3',
    messagingSenderId: '684377007786',
    projectId: 'portfolio-m7m7',
    authDomain: 'portfolio-m7m7.firebaseapp.com',
    storageBucket: 'portfolio-m7m7.firebasestorage.app',
    measurementId: 'G-GFGZ6688BX',
  );
}
